# Generated by Django 5.2.17 on 2026-08-25 08:08

import django.contrib.postgres.fields
import django.db.models.deletion
import django.utils.timezone
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Parcel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('parcel_code', models.CharField(help_text='Canonical Parcel ID used by the application for survey lookup.', max_length=32, unique=True)),
                ('source_nid', models.BigIntegerField(blank=True, db_index=True, help_text="Original hidden 'NID' Excel column B value. Not unique by design.", null=True)),
                ('village', models.CharField(blank=True, max_length=128, null=True)),
                ('tehsil', models.CharField(blank=True, max_length=96, null=True)),
                ('district', models.CharField(blank=True, max_length=96, null=True)),
                ('owner_name_current', models.CharField(blank=True, max_length=255, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'parcel',
                'verbose_name_plural': 'parcels',
                'db_table': 'parcels',
            },
        ),
        migrations.CreateModel(
            name='ImportBatch',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('source_filename', models.CharField(max_length=512)),
                ('file_checksum', models.CharField(db_index=True, help_text='SHA-256 of the imported source workbook (doc 01 pinning).', max_length=64)),
                ('sheet_name', models.CharField(blank=True, max_length=128, null=True)),
                ('total_rows', models.PositiveIntegerField(default=0)),
                ('successful_rows', models.PositiveIntegerField(default=0)),
                ('failed_rows', models.PositiveIntegerField(default=0)),
                ('warning_count', models.PositiveIntegerField(default=0)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('running', 'Running'), ('completed', 'Completed'), ('failed', 'Failed')], default='pending', max_length=16)),
                ('error_summary', models.JSONField(blank=True, null=True)),
                ('imported_at', models.DateTimeField(auto_now_add=True)),
                ('imported_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='import_batches', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'import batch',
                'verbose_name_plural': 'import batches',
                'db_table': 'import_batches',
            },
        ),
        migrations.CreateModel(
            name='SurveyChange',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('client_uuid', models.UUIDField(default=uuid.uuid4, help_text='Offline idempotency key generated on the device.', unique=True)),
                ('revision_no', models.PositiveIntegerField()),
                ('base_master_row_ids', django.contrib.postgres.fields.ArrayField(base_field=models.BigIntegerField(), default=list, help_text='survey_master ids covered by this revision.', size=None)),
                ('changes', models.JSONField(default=dict, help_text='Field-level diff: {"field": {"from": …, "to": …}}.')),
                ('full_payload', models.JSONField(default=dict, help_text='COMPLETE survey state at this revision (WB2 schema, doc 02 Part E).')),
                ('change_reason', models.CharField(blank=True, max_length=255, null=True)),
                ('changed_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('accepted_at', models.DateTimeField(blank=True, null=True)),
                ('status', models.CharField(choices=[('draft', 'Draft'), ('submitted', 'Submitted'), ('synced', 'Synced'), ('rejected', 'Rejected')], db_index=True, default='draft', max_length=16)),
                ('device_info', models.JSONField(blank=True, null=True)),
                ('changed_by', models.ForeignKey(db_column='changed_by_id', on_delete=django.db.models.deletion.PROTECT, related_name='survey_changes', to=settings.AUTH_USER_MODEL)),
                ('parcel', models.ForeignKey(db_column='parcel_id', on_delete=django.db.models.deletion.PROTECT, related_name='revisions', to='surveys.parcel')),
                ('parent_revision', models.ForeignKey(blank=True, db_column='parent_revision_id', null=True, on_delete=django.db.models.deletion.PROTECT, related_name='child_revisions', to='surveys.surveychange')),
            ],
            options={
                'verbose_name': 'survey revision (append-only)',
                'verbose_name_plural': 'survey revisions (append-only)',
                'db_table': 'survey_changes',
            },
        ),
        migrations.AddField(
            model_name='parcel',
            name='current_revision',
            field=models.ForeignKey(blank=True, db_column='current_revision_id', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='surveys.surveychange'),
        ),
        migrations.CreateModel(
            name='AuditLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('occurred_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('action', models.CharField(max_length=48)),
                ('entity_type', models.CharField(blank=True, max_length=32, null=True)),
                ('entity_id', models.BigIntegerField(blank=True, null=True)),
                ('correlation_id', models.UUIDField(blank=True, db_index=True, null=True)),
                ('details', models.JSONField(blank=True, null=True)),
                ('device_info', models.JSONField(blank=True, null=True)),
                ('ip_address', models.GenericIPAddressField(blank=True, null=True)),
                ('user', models.ForeignKey(blank=True, db_column='user_id', help_text='NULL for system jobs.', null=True, on_delete=django.db.models.deletion.PROTECT, related_name='audit_logs', to=settings.AUTH_USER_MODEL)),
                ('parcel', models.ForeignKey(blank=True, db_column='parcel_id', null=True, on_delete=django.db.models.deletion.PROTECT, related_name='audit_logs', to='surveys.parcel')),
                ('revision', models.ForeignKey(blank=True, db_column='revision_id', null=True, on_delete=django.db.models.deletion.PROTECT, related_name='audit_logs', to='surveys.surveychange')),
            ],
            options={
                'verbose_name': 'audit log entry (append-only)',
                'verbose_name_plural': 'audit log entries (append-only)',
                'db_table': 'audit_logs',
            },
        ),
        migrations.CreateModel(
            name='SurveyImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image_type', models.CharField(choices=[('FRONT', 'Front'), ('SECOND', 'Second/Survey')], max_length=12)),
                ('file_path', models.TextField(help_text='Storage-relative path (never a DB blob).')),
                ('original_filename', models.CharField(blank=True, max_length=255, null=True)),
                ('content_type', models.CharField(blank=True, max_length=64, null=True)),
                ('file_size', models.BigIntegerField(blank=True, null=True)),
                ('checksum_sha256', models.CharField(db_index=True, max_length=64)),
                ('width_px', models.PositiveIntegerField(blank=True, null=True)),
                ('height_px', models.PositiveIntegerField(blank=True, null=True)),
                ('captured_at', models.DateTimeField(blank=True, null=True)),
                ('uploaded_at', models.DateTimeField(auto_now_add=True)),
                ('client_uuid', models.UUIDField(default=uuid.uuid4, unique=True)),
                ('sync_status', models.CharField(choices=[('pending', 'Pending'), ('synced', 'Synced')], default='pending', max_length=12)),
                ('parcel', models.ForeignKey(db_column='parcel_id', help_text='Denormalized from revision for direct parcel queries.', on_delete=django.db.models.deletion.PROTECT, related_name='images', to='surveys.parcel')),
                ('revision', models.ForeignKey(db_column='revision_id', on_delete=django.db.models.deletion.PROTECT, related_name='images', to='surveys.surveychange')),
                ('uploaded_by', models.ForeignKey(blank=True, db_column='uploaded_by_id', null=True, on_delete=django.db.models.deletion.PROTECT, related_name='uploaded_images', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'survey image',
                'verbose_name_plural': 'survey images',
                'db_table': 'survey_images',
            },
        ),
        migrations.CreateModel(
            name='SurveyMaster',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('source_row_number', models.PositiveIntegerField(help_text='Physical Excel row number this record was imported from.')),
                ('sr_no', models.PositiveIntegerField(help_text="Excel column A 'Sr. No' counter (verbatim).")),
                ('source_nid', models.BigIntegerField(blank=True, db_index=True, help_text="Excel hidden column B 'NID' (raw, never normalized destructively).", null=True)),
                ('chainage_m', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('affected_persons_count', models.IntegerField(blank=True, null=True)),
                ('phase_code', models.CharField(blank=True, max_length=16, null=True)),
                ('latitude', models.DecimalField(blank=True, decimal_places=7, max_digits=10, null=True)),
                ('longitude', models.DecimalField(blank=True, decimal_places=7, max_digits=10, null=True)),
                ('project_component', models.CharField(max_length=64)),
                ('owner_name', models.CharField(max_length=255)),
                ('father_name', models.CharField(blank=True, max_length=255, null=True)),
                ('caste', models.CharField(blank=True, max_length=96, null=True)),
                ('village', models.CharField(max_length=128)),
                ('tehsil', models.CharField(blank=True, max_length=96, null=True)),
                ('district', models.CharField(blank=True, max_length=96, null=True)),
                ('ownership_documents', models.CharField(blank=True, max_length=255, null=True)),
                ('structure_status', models.CharField(max_length=64)),
                ('structure_name', models.CharField(blank=True, max_length=255, null=True)),
                ('structure_count', models.IntegerField(blank=True, null=True)),
                ('tenure_status', models.CharField(blank=True, max_length=16, null=True)),
                ('length_ft', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('width_ft', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('area_value', models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True)),
                ('construction_nature', models.CharField(blank=True, max_length=32, null=True)),
                ('unit_rate_rs', models.IntegerField(blank=True, null=True)),
                ('compensation_million', models.DecimalField(blank=True, decimal_places=6, max_digits=14, null=True)),
                ('impact_extent', models.CharField(max_length=32)),
                ('river_location', models.CharField(blank=True, max_length=16, null=True)),
                ('in_row_yn', models.CharField(blank=True, max_length=4, null=True)),
                ('cl_offset_m', models.IntegerField(blank=True, null=True)),
                ('extra_note', models.CharField(blank=True, max_length=64, null=True)),
                ('is_formula_area', models.BooleanField(default=False)),
                ('is_formula_compensation', models.BooleanField(default=False)),
                ('raw_data', models.JSONField(help_text='All original cells verbatim (column letter -> value).')),
                ('imported_at', models.DateTimeField(auto_now_add=True)),
                ('import_batch', models.ForeignKey(db_column='import_batch_id', on_delete=django.db.models.deletion.PROTECT, related_name='master_rows', to='surveys.importbatch')),
                ('parcel', models.ForeignKey(db_column='parcel_id', on_delete=django.db.models.deletion.PROTECT, related_name='master_lines', to='surveys.parcel')),
            ],
            options={
                'verbose_name': 'survey master record (immutable)',
                'verbose_name_plural': 'survey master records (immutable)',
                'db_table': 'survey_master',
            },
        ),
        migrations.AddConstraint(
            model_name='importbatch',
            constraint=models.CheckConstraint(condition=models.Q(('status__in', ['pending', 'running', 'completed', 'failed'])), name='ck_import_batches_status_valid'),
        ),
        migrations.AddIndex(
            model_name='surveychange',
            index=models.Index(fields=['changed_at'], name='idx_changes_changed_at'),
        ),
        migrations.AddConstraint(
            model_name='surveychange',
            constraint=models.UniqueConstraint(fields=('parcel', 'revision_no'), name='uq_survey_changes_parcel_revision_no'),
        ),
        migrations.AddConstraint(
            model_name='surveychange',
            constraint=models.CheckConstraint(condition=models.Q(('revision_no__gt', 0)), name='ck_survey_changes_revision_no_positive'),
        ),
        migrations.AddConstraint(
            model_name='surveychange',
            constraint=models.CheckConstraint(condition=models.Q(('status__in', ['draft', 'submitted', 'synced', 'rejected'])), name='ck_survey_changes_status_valid'),
        ),
        migrations.AddConstraint(
            model_name='parcel',
            constraint=models.CheckConstraint(condition=models.Q(('parcel_code', ''), _negated=True), name='ck_parcels_code_nonempty'),
        ),
        migrations.AddIndex(
            model_name='auditlog',
            index=models.Index(fields=['parcel', 'occurred_at'], name='idx_audit_parcel_time'),
        ),
        migrations.AddIndex(
            model_name='auditlog',
            index=models.Index(fields=['user', 'occurred_at'], name='idx_audit_user_time'),
        ),
        migrations.AddIndex(
            model_name='auditlog',
            index=models.Index(fields=['action'], name='idx_audit_action'),
        ),
        migrations.AddConstraint(
            model_name='surveyimage',
            constraint=models.UniqueConstraint(fields=('revision', 'image_type'), name='uq_survey_images_revision_type'),
        ),
        migrations.AddConstraint(
            model_name='surveyimage',
            constraint=models.CheckConstraint(condition=models.Q(('image_type__in', ['FRONT', 'SECOND'])), name='ck_survey_images_type_valid'),
        ),
        migrations.AddConstraint(
            model_name='surveyimage',
            constraint=models.CheckConstraint(condition=models.Q(('file_size__isnull', True), ('file_size__gte', 0), _connector='OR'), name='ck_survey_images_size_nonnegative'),
        ),
        migrations.AddConstraint(
            model_name='surveyimage',
            constraint=models.CheckConstraint(condition=models.Q(('sync_status__in', ['pending', 'synced'])), name='ck_survey_images_sync_status_valid'),
        ),
        migrations.AddIndex(
            model_name='surveymaster',
            index=models.Index(fields=['village'], name='idx_master_village'),
        ),
        migrations.AddIndex(
            model_name='surveymaster',
            index=models.Index(fields=['structure_status'], name='idx_master_struct_status'),
        ),
        migrations.AddConstraint(
            model_name='surveymaster',
            constraint=models.UniqueConstraint(fields=('import_batch', 'source_row_number'), name='uq_survey_master_batch_source_row'),
        ),
        migrations.AddConstraint(
            model_name='surveymaster',
            constraint=models.CheckConstraint(condition=models.Q(('sr_no__gt', 0)), name='ck_master_sr_no_positive'),
        ),
        migrations.AddConstraint(
            model_name='surveymaster',
            constraint=models.CheckConstraint(condition=models.Q(('source_row_number__gt', 0)), name='ck_master_source_row_positive'),
        ),
    ]
