# Generated by Django 5.2.17 on 2026-08-26 21:34

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('surveys', '0003_userprofile'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='surveyimage',
            name='ck_survey_images_type_valid',
        ),
        migrations.AddField(
            model_name='parcel',
            name='khasra_number',
            field=models.CharField(blank=True, max_length=64, null=True),
        ),
        migrations.AddField(
            model_name='parcel',
            name='mauza_number',
            field=models.CharField(blank=True, max_length=64, null=True),
        ),
        migrations.AddField(
            model_name='surveymaster',
            name='khasra_number',
            field=models.CharField(blank=True, help_text='Khasra/plot number assigned during field survey.', max_length=64, null=True),
        ),
        migrations.AlterField(
            model_name='surveyimage',
            name='image_type',
            field=models.CharField(choices=[('FRONT', 'Front'), ('SECOND', 'Second/Survey'), ('POINT_1', 'Point Image 1'), ('POINT_2', 'Point Image 2')], max_length=12),
        ),
        migrations.AddConstraint(
            model_name='surveyimage',
            constraint=models.CheckConstraint(condition=models.Q(('image_type__in', ['FRONT', 'SECOND', 'POINT_1', 'POINT_2'])), name='ck_survey_images_type_valid'),
        ),
    ]
