# Generated by Django 5.2.17 on 2026-08-27 04:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('surveys', '0004_remove_surveyimage_ck_survey_images_type_valid_and_more'),
    ]

    operations = [
        migrations.AddIndex(
            model_name='parcel',
            index=models.Index(fields=['owner_name_current'], name='idx_parcels_owner_name'),
        ),
    ]
