# Generated by Django 5.2.17 on 2026-08-30 18:30

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('surveys', '0006_surveyimage_gps_fields'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='surveyimage',
            name='ck_survey_images_type_valid',
        ),
        migrations.AlterField(
            model_name='surveyimage',
            name='image_type',
            field=models.CharField(choices=[('FRONT', 'Front'), ('SECOND', 'Second/Survey'), ('POINT_1', 'Point Image 1'), ('POINT_2', 'Point Image 2'), ('POINT_3', 'Point Image 3'), ('POINT_4', 'Point Image 4')], max_length=12),
        ),
        migrations.AddConstraint(
            model_name='surveyimage',
            constraint=models.CheckConstraint(condition=models.Q(('image_type__in', ['FRONT', 'SECOND', 'POINT_1', 'POINT_2', 'POINT_3', 'POINT_4'])), name='ck_survey_images_type_valid'),
        ),
    ]
