package com.ruda.survey.utils

import android.graphics.Bitmap
import android.graphics.Canvas
import android.graphics.Color
import android.graphics.Paint
import android.graphics.BitmapFactory
import android.graphics.pdf.PdfDocument
import com.ruda.survey.domain.model.SurveyItem

object PdfGenerator {

    fun generate(survey: SurveyItem): ByteArray {
        val document = PdfDocument()
        val pageInfo = PdfDocument.PageInfo.Builder(595, 842, 1).create()
        val page = document.startPage(pageInfo)
        val canvas: Canvas = page.canvas

        val titlePaint = Paint().apply {
            color = Color.parseColor("#0D3B66")
            textSize = 20f
            isFakeBoldText = true
            isAntiAlias = true
        }
        val headerPaint = Paint().apply {
            color = Color.parseColor("#0D3B66")
            textSize = 14f
            isFakeBoldText = true
            isAntiAlias = true
        }
        val bodyPaint = Paint().apply {
            color = Color.BLACK
            textSize = 11f
            isAntiAlias = true
        }
        val linePaint = Paint().apply {
            color = Color.parseColor("#CCCCCC")
            strokeWidth = 0.5f
        }

        var y = 40f

        canvas.drawText("RUDA Survey Report", 40f, y, titlePaint)
        y += 15f
        canvas.drawLine(40f, y, 555f, y, linePaint)
        y += 25f

        canvas.drawText("SR No: ${survey.srNo}", 40f, y, headerPaint)
        y += 20f
        if (survey.parcelId.isNotBlank()) {
            canvas.drawText("Parcel ID: ${survey.parcelId}", 40f, y, bodyPaint)
            y += 16f
        }
        canvas.drawText("Village: ${survey.village}", 40f, y, bodyPaint)
        y += 16f
        canvas.drawText("Owner: ${survey.ownerName}", 40f, y, bodyPaint)
        y += 16f
        canvas.drawText("Father: ${survey.fName}", 40f, y, bodyPaint)
        y += 16f
        canvas.drawText("CNIC: ${survey.cnic}", 40f, y, bodyPaint)
        y += 16f
        canvas.drawText("Phone: ${survey.phone}", 40f, y, bodyPaint)
        y += 16f
        if (survey.landOwnerDoc.isNotBlank()) {
            canvas.drawText("Land Owner Doc: ${survey.landOwnerDoc}", 40f, y, bodyPaint)
            y += 16f
        }
        y += 10f

        canvas.drawLine(40f, y, 555f, y, linePaint)
        y += 20f
        canvas.drawText("Location Details", 40f, y, headerPaint)
        y += 20f
        canvas.drawText("Khasra No: ${survey.khasraNo}", 40f, y, bodyPaint)
        y += 16f
        canvas.drawText("Land Area: ${survey.landArea}", 40f, y, bodyPaint)
        y += 16f
        canvas.drawText("Electricity: ${survey.electricityConnectionName}", 40f, y, bodyPaint)
        y += 16f
        canvas.drawText("GPS: ${survey.lat}, ${survey.lng}", 40f, y, bodyPaint)
        y += 25f

        canvas.drawLine(40f, y, 555f, y, linePaint)
        y += 20f
        canvas.drawText("Structure Details", 40f, y, headerPaint)
        y += 20f
        canvas.drawText("Structure: ${survey.structuralName}", 40f, y, bodyPaint)
        y += 16f
        canvas.drawText("Status: ${survey.status}", 40f, y, bodyPaint)
        y += 16f
        canvas.drawText("Construction: ${survey.natureOfConstruction}", 40f, y, bodyPaint)
        y += 16f
        canvas.drawText("RD: ${survey.rd}", 40f, y, bodyPaint)
        y += 16f
        canvas.drawText("Package: ${survey.pkg}", 40f, y, bodyPaint)
        y += 16f
        canvas.drawText("Length: ${survey.length}", 40f, y, bodyPaint)
        y += 16f
        canvas.drawText("Width: ${survey.width}", 40f, y, bodyPaint)
        y += 16f
        canvas.drawText("Area: ${survey.area}", 40f, y, bodyPaint)
        y += 25f

        val images = mutableListOf<Pair<String, ByteArray?>>()
        if (survey.image1Bytes != null) images.add("Door Pic" to survey.image1Bytes)
        if (survey.image2Bytes != null) images.add("Front View" to survey.image2Bytes)

        if (images.isNotEmpty()) {
            canvas.drawLine(40f, y, 555f, y, linePaint)
            y += 20f
            canvas.drawText("Images", 40f, y, headerPaint)
            y += 20f

            for ((label, imgBytes) in images) {
                if (y + 160 > 842) break
                val bitmap = BitmapFactory.decodeByteArray(imgBytes, 0, imgBytes!!.size)
                if (bitmap != null) {
                    canvas.drawText("$label:", 40f, y, bodyPaint)
                    y += 16f
                    val scaled = Bitmap.createScaledBitmap(bitmap, 200, 120, true)
                    canvas.drawBitmap(scaled, 40f, y, null)
                    y += 130f
                }
            }
        }

        canvas.drawLine(40f, y, 555f, y, linePaint)
        y += 20f
        canvas.drawText("Generated by RUDA Survey App", 40f, y, bodyPaint)

        document.finishPage(page)

        val outputStream = java.io.ByteArrayOutputStream()
        document.writeTo(outputStream)
        document.close()

        return outputStream.toByteArray()
    }
}
